version: '2'
services:
  transcoder:
    env_file: dev.env
    build:
      context: .
      dockerfile: Dockerfile.local
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    volumes:
      - /Users/sloffler/Code/transcoder-test-folders:/mount
